### PR TITLE
+ Added session destroy on bind error. Calling destroy will clean up …

### PR DESCRIPTION
**Pull request by koeff**
…resources such as WindowMonitor for proper session close and clean up.

Issue: https://github.com/RestComm/cloudhopper-smpp/issues/9

@see also
https://github.com/twitter/cloudhopper-smpp/issues/45
https://github.com/twitter/cloudhopper-smpp/commit/ba14f94e7d2f84cad198e6bafaa6a15ac6fdfce4

### CODE REVIEW

**Comment by gsaslis** [comment]
@koeff thanks for contributing!! 

is this still WIP ? 
(asking because travis tests are failing, and that will be blocking us reviewing this pr)

**Comment by koeff** [comment]
It isn't WIP, unstable test `com.cloudhopper.smpp.tlv.TlvTest` failed (https://travis-ci.org/RestComm/cloudhopper-smpp/builds there are the same failed builds).

**Comment by gsaslis** [comment]
Ok, thanks @koeff and apologies for the terribly late reply here. 

Could you please take a look at our [Open Source Playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.6munton4izwb) and then proceed with signing our [CLA](https://www.restcomm.com/contributor-license-agreement/), so we can then move forward with reviewing this?

Thanks in advance!
Yorgos

**Comment by koeff** [comment]
Have signed CLA

**Comment by gsaslis** [comment]
thanks @koeff ! 

Passing this on for review to our @RestComm/messaging-squad ;)

**Comment by FerUy** [comment]
Thanks @koeff for your contribution 👍 and sorry again for the delayed review.
Your PR is now merged 🥇

**Pull request merged**
