### PR TITLE
added new method parseShortMessage

### PR DESCRIPTION
**Pull request by JChrist**
It offers an extra boolean whether fields should be validated
Also added tests to check that by default it validates fields, throwing
an exception on mismatch, whilst the new method does not

### CODE REVIEW

**Comment by deruelle** [comment]
https://github.com/RestComm/cloudhopper-smpp/issues/15

**Comment by vetss** [comment]
Hello @JChrist 

I see you opened also two other PRs 16 and 17 and closed then further. Do you mean this one is your final version that we need to check ?

**Comment by JChrist** [comment]
Hi @vetss ! As I tried to explain in the gitter channel, I kind of messed up with the other two PRs. This final version is the correct one (similar to the first one #15 ), with added tests.
It still fails due to compilation error (which is the case for restcomm/netty4 branch as well).

**Comment by JChrist** [comment]
@vetss I found the source of the error, it's due to invalid SLF4J version, an updated one is required, 
e.g.  adding in properties section of pom.xml `<slf4j.version>1.7.25</slf4j.version>`
I had already updated that in fizzed/netty4, with commit: https://github.com/fizzed/cloudhopper-smpp/commit/fa36ebc9fd9fad30b5d640bd8ed1edd96f2b5e40

Please advise how you want me to proceed: 
Simply add SLF4J to address the issue, bring this branch up to the latest changes in fizzed/netty4, or perhaps something else?

**Comment by vetss** [comment]
Hello, I added your PR into master and netty4 branches, check my comments in https://github.com/RestComm/cloudhopper-smpp/issues/15

**Pull request closed without merging**
