### PR TITLE
Allow skipping field validation in DeliveryReceipt parseShortMessage 

### PR DESCRIPTION
**Pull request by JChrist**
As mentioned in issue #15 the static method `parseShortMessage` in `DeliveryReceipt` did not allow skipping field validation, throwing an exception if a field did not match the validation requirements.
This might not always be desired, e.g. in the case of validating that the `err` field is at most 3 characters.

### CODE REVIEW

**Comment by JChrist** [comment]
I haven't added any new tests, since I have trouble compiling the project, executing `mvn clean package` results in compilation errors.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ch-smpp: Compilation failure: Compilation failure:
[ERROR] /local/jchrist/projects/cloudhopper-smpp/src/main/java/com/cloudhopper/smpp/impl/DefaultSmppServer.java:[238,24] error: incompatible types: String cannot be converted to Marker
[ERROR] /local/jchrist/projects/cloudhopper-smpp/src/main/java/com/cloudhopper/smpp/impl/DefaultSmppServer.java:[281,20] error: incompatible types: String cannot be converted to Marker
```

Can you please advise what I might be doing wrong?
My plan is that once I fix the compilation issue, I will add tests and then backport the change to master

**Comment by deruelle** [comment]
@JChrist can you please sign the Contributor License Agreement at https://telestax.com/open-source/#Contribute so we can accept your contributions ?

**Comment by JChrist** [comment]
Hi @deruelle ! Thanks for your quick response!
I just submitted the agreement.
The CI failure is similar to the one I am referring to.

**Comment by deruelle** [comment]
Thanks @JChrist. @vetss can you please review  this PR  ?

**Pull request closed without merging**
